### PR TITLE
Return rpc_ok with label from original RPC request

### PR DESCRIPTION
**Pull request by jsimmonds2**
Fixes [this post in FarmBot Forum](https://forum.farmbot.org/t/farmware-moveabsolute-and-executesequence-not-working/5784/40).

### CODE REVIEW

**Comment by RickCarlino** [comment]
Thanks for looking in to this @jsimmonds2 . How far have you QAed this, and do you think it is ready to merge? I can merge (and start a formal round of QA) if you think it is.

**Comment by jsimmonds2** [comment]
@RickCarlino I've QAed as far as I know how :)
* FBOS boots up cleanly.
* Long Sequences run normally.
* The **`Hello Farmware Test`** package supplied by @whitecapsO now runs at maximum possible speed.

Yes, I believe that formal QA should start on this fix. It only seems to affect Farmware execution.

**Comment by RickCarlino** [comment]
Sounds good @jsimmonds2 and thanks again for your help in debugging this matter. :tada:

**Comment by whitecapsO** [comment]
Thanks guys if you want me to QA test let me know. I assume I just load the latest OS and run some Farmwares and see what happens?

**Comment by jsimmonds2** [comment]
@whitecapsO , you'd need to watch for the **v9.0.4** Release  ( or later ) . . unless you want to build your own clone / fork in **staging** branch (?)

**Comment by RickCarlino** [comment]
@whitecapsO @jsimmonds2 I can build a beta release that can be manually flashed.

**Comment by RickCarlino** [comment]
@whitecapsO @jsimmonds2 The release candidate is available here: https://github.com/FarmBot/farmbot_os/releases/tag/untagged-cf514d15d8204e9c9524

You may need to manually flash this one. I have not QAed this specific release yet, but I did QA a previous release last night and everything seemed OK. Please let me know if you have any issues and I can take a look. Again, this is a *beta release* so it may still have some quality issues.

**Comment by RickCarlino** [comment]
@whitecapsO @jsimmonds2 Just a heads up that `v9.1.0-rc16` is now in the "beta" phase (rc1-15 were QAed internally), and it contains a newer version of the firmware.

**Comment by jsimmonds2** [comment]
@RickCarlino , thanks !  Your team is doing an impressive stretch effort 🥇 
I'll play around with **`v9.1.0-rc16`** today.

**Comment by jsimmonds2** [comment]
Can't break it 🤸‍♂   but you know I don't have any hardware on the Farduino v1.4 board 🙂  (yet)

**Comment by jsimmonds2** [comment]
@RickCarlino Great effort !

I'm up on **`v9.1.0`** and noticed that it has the older ( `6.4.2` Firmware ) vs the `6.5.5` firmware bundled with **`v9.1.0-rc16`** 😕
I'm sure that's intentional, but am having a devil of a time working out how a certain firmware version gets into a Release artefact !
That's for me to ponder while you keep this high-speed train on the rails 👍

**Comment by RickCarlino** [comment]
@jsimmonds2 This release was, admittedly, a bit rushed. As a result, we decided to take the cautious approach and only release the new firmware that we knew customers needed (we're getting reports of problems from some early Express users). We didn't have time to QA the firmware on other platforms as well as we would have liked, so we decided late last night to only upgrade the Express firmware.

How was your experience on `-rc16`? I run an old v1.2 bot here in Chicago and although rc16 works great with 1.2 hardware, there were some hiccups in earlier RC's. Curious to hear your perspective.

**Comment by jsimmonds2** [comment]
@RickCarlino 

> although rc16 works great with 1.2 hardware, there were some hiccups in earlier RC's. Curious to hear your perspective.

I don't have a complete bot.  I have the 24V FarmBot power supply + Raspberry Pi 3 Model B Plus + Farmduino v1.4 with nothing wired to it.

If Rory remembers his earlier promise, I should soon be the proud owner of a Genesis v1.5 kit !
( a gift that he and Connor arranged for my informal QA and debugging work in FBOS in 2019 )

**Comment by RickCarlino** [comment]
We haven't forgot about you @jsimmonds2 :stuck_out_tongue_winking_eye: The packages are shipping very soon (this month).

**Comment by whitecapsO** [comment]
I have tested my Farmware on FBOS 9.1.0 it works fine and runs a bit faster. Thanks again.  @jsimmonds2 if you need any help\advice setting up the new bot feel free to message me.

**Pull request merged**
