### PR TITLE
Plug lost farm events after FBOS reboot

### PR DESCRIPTION
**Pull request by jsimmonds2**
Restrain `FarmEventWorker.SequenceEvent` until `NervesTime.synchronized?` true.

Fix defect where `FarmEventWorker.SequenceEvent` process calls **`build_calendar/1`** long before the OS time is brought into the 21st Century. This causes **all** occurrences for all Sequence FarmEvents to be generated and re-processed thus potentially leading to long delays before any Sequence occurrence actually executes on the 1-CPU Express models following an FBOS reboot.

### CODE REVIEW

**Comment by RickCarlino** [comment]
Great work @jsimmonds2 ! I assume this is the same issue we discussed a few weeks ago?

**Comment by jsimmonds2** [comment]
@RickCarlino Yes same issue precisely.

Wasn't sure how to add tests so will need guidance if those are required. Thanks !

**Comment by RickCarlino** [comment]
@jsimmonds2 Tests would be nice, but if they feel overwhelming, that's fine I can take care of that for you. A good starting point would be to read a [tutorial about ExUnit](https://elixirschool.com/en/lessons/basics/testing/) and then take a look at the [documentation for Mimic](https://github.com/edgurgel/mimic). We use Mimic to stub things out and generally fake the behavior of systems that would be impossible to use in a unit test (example: we can't run motors in a unit test because there are no motors).

Our goal is to make sure that unit tests touch every line of code we add or change in the code base.

You can check if the unit test hits the lines of code by performing the following:

0. `cd farmbot_core/`
0. `mix coveralls.html`
0. The unit tests will run (albeit a little slower than `mix test`). At the end of the test run, it will show the file location of an HTML coverage report.
0. Open the HTML file from the previous step. All of the lines you've added/updated should be green. If they ar not green, the lines are untested.

Feel free to PM me on the forum if you have specific questions about unit testing. We appreciate outside contributions and are willing to add tests on our end if you hit problems. Admittedly, _Elixir is not an easy language to test_ due to the parallel and immutable nature of the language so it does take some time to learn the process, even if you are already familiar with unit testing in other languages.

**Comment by jsimmonds2** [comment]
> Feel free to PM me on the forum if you have specific questions about unit testing. We appreciate outside contributions and are willing to add tests on our end if you hit problems

Please add appropriate tests.  I learn fastest by a 'monkey-see monkey-do' approach 😉 If I join your team as a Contractor I will need to supply tests !

[ JavaScript (ECMAscript) testing was **_**so**_** much easier and almost zero invasive of source code 🙂 ]

**Comment by RickCarlino** [comment]
@jsimmonds2 FYI That I've updated this branch with the large changeset for v14.3

**Comment by jsimmonds2** [comment]
This one missed the bus. Will make a new PR now that activity has slowed a little.

**Pull request closed without merging**
