### PR TITLE
Add Features #792 and #1132

### PR DESCRIPTION
**Pull request by jsimmonds2**
Draft PR for shakedown and beta.

Test code in a future PR.

### CODE REVIEW

**Comment by gabrielburnworth** [comment]
I've made some changes (see https://github.com/jsimmonds2/farmbot_os/compare/Features_792_and_1132...FarmBot:qa/15.1.0) and released it as `v15.1.0-rc0` on the `alpha` channel.

**Comment by jsimmonds2** [comment]
@gabrielburnworth Humble apologies !  I totally overlooked the **`mix format`** pre-requisite :(

How do I proceed to amend this ?  Delete the PR and make a new one ?  Update this ?
Your advice is welcome.

**Comment by gabrielburnworth** [comment]
No worries; it's easy to overlook. You may update this PR.

You'll want to merge this into your branch first via the button on the page or `git`: https://github.com/jsimmonds2/farmbot_os/compare/Features_792_and_1132...FarmBot:qa/15.1.0

Then you can run `mix format` and commit that as well. 

I usually use `git`, so I would:
```
git clone https://github.com/jsimmonds2/farmbot_os
cd farmbot_os
git remote add upstream https://github.com/farmbot/farmbot_os
git checkout Features_792_and_1132
git pull upstream qa/15.1.0
git pull upstream qa/boot_job
mix format
git add .
git commit -m 'fix formatting'
git push origin Features_792_and_1132
```

Let me know if you have any questions. I'm not sure if you have any local changes already, but if you do and have any trouble merging I can merge those branches in after if you prefer.

**Comment by jsimmonds2** [comment]
Closed due to being too time-poor to finish things and being overall-code-savvy-poor . . . Best wishes :)

**Pull request merged**
