### PR TITLE
Create Tuskegee University Farmbot

### PR DESCRIPTION
**Pull request by CamJ43737**
image

image

### CODE REVIEW

**Comment by CamJ43737** [comment]
Good afternoon Farmbot.io! My name is Cameron Jones, student of the illustrious Tuskegee University. I am a cs major partnered with our CAENS program. As we embarked on research using our farmbot we have had a couple of issues, but we have managed to overcome them. We however have been stumped as our farmbot os had recently stopped functioning all together. In an effort to get it working again we flashed the software, following your instructions on your website. It was successful, however we cannot run any of our sequences. The farmbot will move it we instruct it to manually, but not through any of our sequences. We have also gotten errors everytime we try to run a sequence. The main one is: {:timeout, {GenServer, :call, [FarmbotOS.Firmware.UARTCore, {:start_job, %FarmbotOS.Firmware.GCode{command: :G00, echo: nil, params: [X: 1.1e3, Y: 709.8, Z: 0, A . We could use some assistance at your earliest convenience. My email is cameron.kalo@gmail.com and my number is 6156006272. Please get back to me whenever you can. Thank you.

**Comment by CamJ43737** [comment]
Good afternoon Farmbot.io! My name is Cameron Jones, student of the illustrious Tuskegee University. I am a cs major partnered with our CAENS program. As we embarked on research using our farmbot we have had a couple of issues, but we have managed to overcome them. We however have been stumped as our farmbot os had recently stopped functioning all together as a result of accidentally unplugging the bot during its return to home in our watering sequence. In an effort to get it working again we flashed the software, following your instructions on your website. It was successful, however we cannot run any of our sequences. The farmbot will move it we instruct it to manually, but not through any of our sequences. We have also gotten errors everytime we try to run a sequence. The main one is: {:timeout, {GenServer, :call, [FarmbotOS.Firmware.UARTCore, {:start_job, %FarmbotOS.Firmware.GCode{command: :G00, echo: nil, params: [X: 1.1e3, Y: 709.8, Z: 0, A . We could use some assistance at your earliest convenience. My email is [cameron.kalo@gmail.com](mailto:cameron.kalo@gmail.com) and my number is 6156006272. Please get back to me whenever you can. Thank you.

**Comment by roryaronson** [comment]
@CamJ43737 we have reached out to you privately over email to help resolve your issue. In the future, please only open Pull Requests for software contributions. For customer support, you can email us at support@farm.bot.

While I am unable to delete your PR, I will edit the content to remove your personal contact information. Thank you for your understanding

**Comment by CamJ43737** [comment]
Thanks Rory I had closed it earlier today but I may have had more than one.
Very much appreciated. We will try your suggestions from the call earlier
today and let you know how it goes. We will also send screenshots of the
log screen.

Regards,
𝒞𝒶𝓂𝑒𝓇𝑜𝓃 𝒥𝑜𝓃𝑒𝓈
Sophomore, Computer Science Major

Tuskegee University Ambassador

**Pull request closed without merging**
